### ISSUE TITLE
Can you help me implement something?

### ISSUE THREAD

**Issue by talmax1124** [keremcanb/ecommerce-app-mern-stack#1]

**Comment by keremcanb** [comment]
What do you want me to do?

**Comment by talmax1124** [comment]
Ok, I did the same course as you, I have implemented various things my self by tutorials and other forms. But I cannot achieve doing options. What I mean by this is like having different options and prices for each individual item. So like If I want to have a iphone and a shirt then I want to have the options for the iphone to be like 100gb for the reg price, then a variant of 256 for like 30 dollars more and so on. And like for the shirt for it to be like a different price for each shirt size. 

If you get what I mean. I have been trying to implement this but I have been unsuccessful. Oh and 1 more thing, if you could tell me how I can integrate changing images into arrays. If you could help me, it would be really helpful. Thanks! 

@keremcanb

**Comment by talmax1124** [comment]
For example, this site I found: https://commercejs-demo-store.netlify.app/product/complexion-cream is sort of what I have been trying to accomplish @keremcanb

**Comment by talmax1124** [comment]
Will you be able to help me?

**Comment by keremcanb** [comment]
John Smilga has a really good React course. It has an ecommerce project with features you want. You dont have to take the course, his code is available at Github. I suggest you take a look at it and implement to your project. https://github.com/john-smilga/react-course-comfy-sloth-store

**Comment by talmax1124** [comment]
Is the feature I'm wanting in it? Also is there a course link?

**Comment by talmax1124** [comment]
Ok, I saw the feature I'm looking for, but how does he manage the colors? Does he do it in his database? @keremcanb

**Comment by talmax1124** [comment]
I can't figure out how he got his colors, I saw that in the Utils he had a URL that had the colors and the products. If you had to do it, how would you do it? Any Suggestions or can you help me out. Also something that is urgent is order status. In the orderscreen or orderList, I want to be able to change the orderStatus of the order. I already have the model in the database and most of the code done, just need to implement something to pass to the database and UI. That's something he did not have

**Comment by talmax1124** [comment]
I just forgot, to mention also that he only has one sort of options and is not the same thing. Because I have various example products like Shirts, Iphones, Cameras, etc. And like stated before, he only has colors that are not even from a database, i don't know how to implement it. Would it be possible for you to assist? @keremcanb

**Comment by keremcanb** [comment]
Mate, I'm also busy with my own projects can't help you personally. Just find similar code and modify it to your needs.

**Comment by talmax1124** [comment]
Since you are an experienced dev, I thought you were able to help me real quick. I am trying to accomplish this but I understand your POV. sorry

**Comment by talmax1124** [comment]
Can you at least help me out in the options thing?
